from tkinter import *
from reportlab.platypus import SimpleDocTemplate,Paragraph,Table,TableStyle
from reportlab.lib import colors
def feestruc():
	import webbrowser
	root=Tk()
	root.wm_title('ADD NEW FEE STRUC')
	root.geometry("1000x700")
	Label(root,text="ENTER DATA FOR NEW CLASS",font=20).place(x=400,y=0)
	CLASS=Entry(root,width=50,bd=5)
	CLASS.place(x=400,y=30)
	BF=Entry(root,width=50,bd=5)
	BF.place(x=400,y=65)
	UF=Entry(root,width=50,bd=5)
	UF.place(x=400,y=100)
	SF=Entry(root,width=50,bd=5)
	SF.place(x=400,y=135)
	SEF=Entry(root,width=50,bd=5)
	SEF.place(x=400,y=170)
	SG=Entry(root,width=50,bd=5)
	SG.place(x=400,y=205)
	SCIF=Entry(root,width=50,bd=5)
	SCIF.place(x=400,y=240)
	FINE=Entry(root,width=50,bd=5)
	FINE.place(x=400,y=275)
	PHEDU=Entry(root,width=50,bd=5)
	PHEDU.place(x=400,y=310)
	LIB=Entry(root,width=50,bd=5)
	LIB.place(x=400,y=345)
	EXAM=Entry(root,width=50,bd=5)
	EXAM.place(x=400,y=380)
	FUR=Entry(root,width=50,bd=5)
	FUR.place(x=400,y=415)
	CULT=Entry(root,width=50,bd=5)
	CULT.place(x=400,y=450)
	MAG=Entry(root,width=50,bd=5)
	MAG.place(x=400,y=485)
	ICARD=Entry(root,width=50,bd=5)
	ICARD.place(x=400,y=520)
	CLAS_S=Label(root,text="CLASS     ")
	CLAS_S.place(x=300,y=30)
	B_F=Label(root,text="BUILDING FUND")
	B_F.place(x=300,y=65)
	U_F=Label(root,text="UNION FUND   ")
	U_F.place(x=300,y=100)
	S_F=Label(root,text="SPORTS FUND  ")
	S_F.place(x=300,y=135)
	SE_F=Label(root,text="SPORT EQ FUND")
	SE_F.place(x=300,y=170)
	S_G=Label(root,text="SCOUT & GUIDE")
	S_G.place(x=300,y=205)
	SCI_F=Label(root,text="SCIE. FUND")
	SCI_F.place(x=300,y=240)
	FIN_E=Label(root,text="FINE FUND")
	FIN_E.place(x=300,y=275)
	PHED_U=Label(root,text="PHYSICAL FUND")
	PHED_U.place(x=300,y=310)
	LIB_=Label(root,text="LIB FUND")
	LIB_.place(x=300,y=345)
	EXAM_=Label(root,text="EXAM FUND")
	EXAM_.place(x=300,y=380)
	FUR_=Label(root,text="FURNITURE FUND")
	FUR_.place(x=300,y=415)
	CULT_=Label(root,text="CULTURAL FUND")
	CULT_.place(x=300,y=450)
	MAG_=Label(root,text="MAGAZINE FUND")
	MAG_.place(x=300,y=485)
	ICARD_=Label(root,text="ICARD FUND")
	ICARD_.place(x=300,y=520)
	def add():
		import sqlite3
		con=sqlite3.connect('feemanager.db')
		obj=con.cursor()
		b=int(CLASS.get())
		obj.execute("SELECT Class FROM	feerate")
		o=obj.fetchall()
		g=0
		for i in o:
			for j in i:
				g=j
				if(g==b):
					break
			if(g==b):
				break
		if(g!=b):		
			nam=int(CLASS.get()),int(BF.get()),int(UF.get()),int(SF.get()),int(SEF.get()),int(SG.get()),int(SCIF.get()),int(FINE.get()),int(PHEDU.get()),int(LIB.get()),int(EXAM.get()),int(FUR.get()),int(CULT.get()),int(MAG.get()),int(ICARD.get())
			CLASS.delete(0,END)
			BF.delete(0,END)
			UF.delete(0,END)
			SF.delete(0,END)
			SEF.delete(0,END)
			SG.delete(0,END)
			SCIF.delete(0,END)
			FINE.delete(0,END)
			PHEDU.delete(0,END)
			LIB.delete(0,END)
			EXAM.delete(0,END)
			FUR.delete(0,END)
			CULT.delete(0,END)
			MAG.delete(0,END)
			ICARD.delete(0,END)
			obj.execute("INSERT INTO feerate VALUES('%d','%d','%d','%d','%d','%d','%d','%d','%d','%d','%d','%d','%d','%d','%d')"%(nam[0],nam[1],nam[2],nam[3],nam[4],nam[5],nam[6],nam[7],nam[8],nam[9],nam[10],nam[11],nam[12],nam[13],nam[14]))	
			con.commit()
			con.close()
			con=sqlite3.connect('feemanager.db')
			obj2=con.cursor()
			td=[["Class","BF","UF","SF","SEF","SG","SciF","Fine","PhEdu","Lib","Exam","Fur","Cult","mag","Icard"]]
			obj2.execute("SELECT * FROM feerate")
			sh=obj2.fetchall()
			pdf=SimpleDocTemplate("reciept.pdf",title="receipt")
			flow_obj=[]
			for row in sh:
				data=[row[0],row[1],row[2],row[3],row[4],row[5],row[6],row[7],row[8],row[9],row[10],row[11],row[12],row[13],row[14]]
				td.append(data)
			table=Table(td)
			ts=TableStyle([("GRID",(0,0),(-1,-1),3,colors.black),
				("BACKGROUND",(0,0),(-1,0),colors.white)])
			table.setStyle(ts)
			flow_obj.append(table)
			pdf.build(flow_obj)
			con.close()
			webbrowser.open_new(r'reciept.pdf')
		else:
			messagebox.showinfo("INFO","DATA OF THIS CLASS ALLREADYY PRESENT")	
	button=Button(root,text="SUBMIT",command=add)
	button.place(x=500,y=570)
	root.mainloop()